config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homepage#index'

  resources :posts

  resources :categories

  get '/about', to: 'homepage#about'
  get '/cookies', to: 'homepage#cookies'

  get '/my_posts', to: 'posts#user_posts'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  # uniqueness sprawdza unikatowosc, presence nie dopuszcza pustych elementow
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true, uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord
  scope :featured_posts, -> { includes(:categories).order('created_at DESC').limit(10) }
  belongs_to :user
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, :expiration_date, presence: true

  validate :expiration_date_cannot_be_in_the_past

  def expiration_date_cannot_be_in_the_past
    return unless expiration_date && expiration_date < Date.today
    errors.add(:expiration_date, "can't be in the past")
  end
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :fetch_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    # binding.pry # odpala pry w momencie wywolania metody
    # raise params.to_yaml # wyrzuca wyjatek do przegladarki
    return unless params_have_valid_user_id
    @category = Category.new(category_params)
    @category.valid? ? create_post : handle_post_validation_failed
  end

  def show; end

  def edit
    @category
  end

  def update
    @category.update_attributes(category_params)
    redirect_to @category
  end

  def destroy
    @category.destroy
    flash[:notice] = "Category #{@category.name} deleted"
    redirect_to categories_path
  end

  private

  def params_have_valid_user_id
    post_params[:user_id] == current_user.id.to_s
  end

  def handle_post_validation_failed
    flash[:errors] = @category.errors.full_messages
    redirect_back(fallback_location: root_path)
  end

  def create_post
    @category.save
    flash[:notice] = 'Category created!'
    redirect_to @category
  end

  def fetch_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @categories = Category.all
    @featured_posts = Post.featured_posts
  end

  def about; end

  def cookies; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :fetch_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all.reverse
    # Wyswietla ostatnie 5 postow uzytkownika
    # @posts = current_user.posts.last(5)
  end

  def user_posts
    @posts = current_user.posts
  end

  def new
    @post = Post.new
  end

  def create
    # Zabezpieczenie przed podmiana id aktualnie zalogowanego uzytkownika
    # Uniemozliwia dodanie psotu dla innego uzytkownika, niz aktualni zalogowany
    return unless post_params[:user_id] == current_user.id.to_s
    @post = Post.new(post_params)
    if @post.valid?
      @post.save
      flash[:notice] = 'Post created!'
      redirect_to @post
    else
      flash[:errors] = @post.errors.full_messages
      redirect_back(fallback_location: root_path)
    end
  end

  def show; end

  def edit; end

  def update
    @post.update_attributes(post_params)
    redirect_to @post
  end

  def destroy
    @post.destroy
    flash[:notice] = "Post #{@post.title} deleted"
    redirect_to posts_path
  end

  private

  def fetch_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :expiration_date, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin_categories_link
    categories_link_tag = link_to 'Categories', categories_path
    categories_link_tag.html_safe if current_user_is_admin
  end

  def posts_link
    link_to 'Posts', posts_path
  end

  def my_posts_link
    link_to 'My Posts', my_posts_path
  end

  def current_user_is_admin
    current_user && current_user.is_admin?
  end

  def login_or_logout_user_link
    current_user ? logout_user_link : login_user_link
  end

  def login_user_link
    link_to 'Login', new_user_session_path
  end

  def logout_user_link
    link_to 'Logout', destroy_user_session_path, method: :delete
  end

  def register_user_link
    link_to 'Register', new_user_registration_path unless current_user
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_owner(post)
    current_user && post.user_id == current_user.id
  end
end

app/views/categories/_form.haml
= form_for @category do |f|
  = f.label :name
  = f.text_field :name
  = f.submit 'Submit'

app/views/categories/edit.haml
- if current_user_is_admin
  %h2
    Edit category:
    = @category.name
    = link_to 'Delete', @category, method: :delete, data: { confirm: "Are you sure?" }
  = render 'form'

app/views/categories/index.haml
= button_to 'Add new category', new_category_path, method: :get, class: 'btn btn-sm'
%h2= 'Categories:'
- @categories.each do |category|
  %p= link_to category.name.capitalize, category

app/views/categories/new.haml
%h2 New category
= render 'form'

app/views/categories/show.haml
%h2
  = @category.name.capitalize
  = link_to 'Edit', edit_category_path(@category) if current_user_is_admin

app/views/homepage/about.haml
.row
  .container
    .col-xs-4.col-xs-offset-4
      %h2 About us!

app/views/homepage/cookies.haml
.row
  .container
    .col-xs-4.col-xs-offset-4
      %h2 Cookies policy

app/views/homepage/index.haml
.row
  .container
    %h2.text-center What are you looking for today?
    .col-sm-6.col-sm-offset-3
      %input.form-control{placeholder: 'Search...', type: 'Text'}
      .row.text-center
        - @categories.each do |category|
          = link_to category.name.capitalize, category
      .row.text-center
        - @featured_posts.each do |post|
          %p
            = link_to post.title, post
            Categories:
            - post.categories.each do |categories|
              = categories.name

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sellito</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/messeges' %>
    <!--<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>-->
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/posts/_form.haml
= form_for @post do |f|
  %p
    = f.label :title
    = f.text_field :title
  %p
    = f.label :description
    = f.text_area :description
  %p
    = f.label :expiration_date
    = f.date_field :expiration_date
  = f.hidden_field :user_id, value: current_user.id
  %p
    = f.submit 'Submit'

app/views/posts/edit.haml
%h2
  Edit post:
  = @post.title
  = link_to 'Delete', @post, method: :delete, data: { confirm: "Are you sure?" } if post_owner(@post)
= render 'form'

app/views/posts/index.haml
%h2= 'Posts:'
= button_to 'Add new post', new_post_path, method: :get, class: 'btn btn-sm'
- @posts.each do |post|
  %p
    = link_to post.title, post
    = link_to 'Edit', edit_post_path(post) if post_owner(post)

app/views/posts/new.haml
%h2 New post
= render 'form'

app/views/posts/show.haml
%h2
  = @post.title
  = button_to 'Edit', edit_post_path, method: :get, class: 'btn btn-sm' if post_owner(@post)

%p
  = @post.expiration_date.to_date
%p
  = @post.description

app/views/posts/user_posts.haml
%h2= 'My Posts:'
= button_to 'Add new post', new_post_path, method: :get, class: 'btn btn-sm'
- @posts.each do |post|
  %p
    = link_to post.title, post
    = link_to 'Edit', edit_post_path(post)

app/views/shared/_footer.haml
%footer.footer
  .container.text-center
    %p.class-muted
      = link_to "Cookies", cookies_path

app/views/shared/_header.haml
%nav.navbar.navbar-default
  .container.fluid
    .navbar-header
      .navbar-brand
      = link_to image_tag("logo.png",:size => "43x50"), root_path
    %ul.nav.navbar-nav.pull-right
      %li
        = link_to 'Home', root_path
      %li
        = link_to 'About', about_path
      %li
        = posts_link
      - if current_user
        %li.dropdown
          %a.dropdown-toggle{"data-toggle": "dropdown", type: "button"}
            Menu
            %span.caret
            %ul.dropdown-menu
              %li= my_posts_link
              %li= admin_categories_link
      %li
        = login_or_logout_user_link
      %li
        = register_user_link

app/views/shared/_messeges.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-success"}
      %button.close{"aria-hidden": "true", "data-dismiss": "alert", type: "button"} &times;
      = content_tag :div, msg, id: "flash_success"
  - else
    %div{class: "alert alert-danger"}
      %button.close{"aria-hidden": "true", "data-dismiss": "alert", type: "button"} &times;
      - msg.each do |error|
        = content_tag :div, error, id: "flash_errors"